### PR TITLE
Added plugins the ability to also generate free functions.

### PR DESCRIPTION
**Pull request by peci1**
Solves #39 .

### CODE REVIEW

**Comment by peci1** [comment]
There are no automated tests, but I tried that with a package and I was able to define a free function that uses the generated message class.

**Comment by dirk-thomas** [comment]
Wouldn't it be much easier to optionally include another file at the end - similar to https://github.com/ros/gencpp/blob/40559afd553c9bdcc3a959fd3ba02c1ad38ef495/scripts/msg.h.template#L63-L65 ? Having to write a significant code block within a macros seems cumbersome.

**Comment by peci1** [comment]
I was thinking about that, too, but isn't one "magic" file enough? But of course it can be done. What about `Message.after.h`?

**Comment by peci1** [comment]
And unfortunately you cannot do 

    #include <MY_ELSEWHERE_DEFINED_PREPROCESSOR_DEFINE>

**Comment by dirk-thomas** [comment]
> I was thinking about that, too, but isn't one "magic" file enough?

If you want to write significant amount of code I think a new file is a tiny burden compared to wrapping everything in a macro (which usually means you use all editor support for the code you write).

> What about `Message.after.h`?

Sounds good to me.

**Comment by peci1** [comment]
I made the change.

**Comment by dirk-thomas** [comment]
Please also extend the docs in http://wiki.ros.org/roscpp/Overview/MessagesSerializationAndAdaptingTypes#Customizing_generated_message_headers_for_C.2B-.2B- with this new feature. Use the next patch version 0.6.2 as the one as of which this feature will be available. Please post a link to the diff here for future readers to find the changes.

**Review by dirk-thomas — APPROVED** [review]

**Comment by peci1** [comment]
Wiki is done: http://wiki.ros.org/action/info/roscpp/Overview/MessagesSerializationAndAdaptingTypes?action=diff&rev2=17&rev1=16 .

**Comment by dirk-thomas** [comment]
Thanks for implementing | documenting this new feature.

**Pull request merged**
