### PR TITLE
Deprecate message connection header to get ready for removal

### PR DESCRIPTION
**Pull request by dirk-thomas**
Replaces #8 merging into hydro-devel branch only.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
@kwatts Can you please remove the added newline in line 129? Just commit to your current branch (and please also squash the commits afterwards). I will go ahead and merge it into the hydro-devel branch then.

**Comment by kwatts** [comment]
@dirk-thomas Done, thanks!

**Comment by dirk-thomas** [comment]
Can you please squash your four commits into one single commit? And line 128 should be changed into line 130 - currently the position of the empty line changes from below to above that line.

**Comment by kwatts** [comment]
All squashed together, should be good.

**Comment by dirk-thomas** [comment]
Thank you for your effort and sorry for being picky :smile:

**Comment by dirk-thomas** [comment]
@kwatts Are you aware that with this patch applied the compiler will output a deprecation warning for every usage of the message class (because of the boost:shared_ptr) (e.g. https://github.com/ros/ros_comm/blob/hydro-devel/clients/roscpp/src/libros/publication.cpp#L173)?

Also on usage of the member variable (`msg->__connection_header`) the compiler does not actually output a deprecation warning (e.g. https://github.com/ros/ros_comm/blob/hydro-devel/tools/topic_tools/src/throttle.cpp#L91).

Since I don't know anyway to achieve the desired behavior (exactly the opposite as it is happening) I reverted the patch (for now).

**Comment by kwatts** [comment]
That is annoying and this is exactly the opposite of what we would want. I
apologize for this.

Can we just remove the field in Indigo? I can submit tested patches for
fixing topic_tools and action_lib.

I think that removing these (mostly) unused bytes will make using ROS
messages to store data much more efficient and help the entire community.

**Comment by dirk-thomas** [comment]
Yes, removing the field in _Indigo_ is fine with me (since there is a much cleaner way to do it already). Patches for other packages would be very welcome. While there is no _indigo-devel_ branch you could still provide the pull requests - I can update them later to apply to the new branch.

**Pull request merged**
