### PR TITLE
python 3 compatibility

### PR DESCRIPTION
**Pull request by dirk-thomas**
@wjwwood Please review.

### CODE REVIEW

**Comment by wjwwood** [comment]
+1

**Comment by tfoote** [comment]
Do these not need ?

```
from __future__ import print_function
```

for 2.7 platform compatibility

**Comment by dirk-thomas** [comment]
In Python 2.7 print works with as well as without parenthesis. You need the import from future when using:

```
print('...', file=sys.stderr)
```

**Comment by tfoote** [comment]
+1

**Comment by dirk-thomas** [comment]
Closing in favor of #11.

**Pull request closed without merging**
